### ISSUE TITLE
Api at yiimp

### ISSUE THREAD

**Issue by napoleon2121** [saltpool/yiimp_install_script#3]
Hello and thank you for the scrypt. Today i will buy your course also. 
i wanted to ask you if yiimp has api in order to use them for inserting the pool at coinminerpools.

Also yiimp supports etherium wallet? 

thank you 
in advance
napoleon

**Comment by saltpool** [comment]
Hi Napoleon,

My apologies for not getting back to you sooner, I didn't see the notification.

Yiimp does indeed have an API that is open to the public, just enter /api at the end of the main pool URL, e.g., saltpool.net/api, for more details.

Yiimp unfortunately does not support Ethereum.

Regards,
Craig
