### ISSUE TITLE
yescrypt algos

### ISSUE THREAD

**Issue by Mining-Blue** [saltpool/yiimp_install_script#4]
yescrypt  /r16/r32 not works?

yiimp@vmi2013349:/var/stratum/config$ ./run.sh yescrypt
11:33:12: ERROR: 13 invalid algo

yiimp@vmi2013349:/var/stratum/config$ ./run.sh yescryptr8
11:33:27: ERROR: 13 invalid algo

yiimp@vmi2013349:/var/stratum/config$ ./run.sh yescryptr16
11:33:38: ERROR: 13 invalid algo

yiimp@vmi2013349:/var/stratum/config$ ./run.sh yescryptr32
11:34:38: ERROR: 13 invalid algo

**Comment by saltpool** [comment]
This is not related to this install script. If there is a issue with an algo that is supported by Yiimp, please create the issue in the Yiimp repo so it can be addressed there.
